<template>
  <nav
    class="
      w-full
      h-16
      flex
      justify-center
      transition-all
      duration-300
      dark:mb-8
    "
  >
    <div class="hidden dark:block">
      <img
        src="@/assets/img/details/toile-2.png"
        class="absolute opacity-20 left-0 transform -translate-x-1/4 -translate-y-16"
      />
      <img
        src="@/assets/img/details/toile-4.png"
        class="absolute max-w-3xl right-0"
      />
    </div>

    <div class="w-full h-full max-w-content relative flex">
      <img
        src="@/assets/img/indice.png"
        alt=""
        class="
          hidden
          dark:block
          absolute
          left-1/2
          transform
          -translate-x-1/2
          h-16
          lg:h-32
        "
      />
      <div
        class="
          bg-primary
          dark:bg-orange-light
          w-screen
          absolute
          right-full
          h-full
        "
      ></div>
      <div
        class="
          bg-primary
          dark:bg-orange-light
          w-screen
          absolute
          left-full
          h-full
        "
      ></div>
      <div
        class="
          bg-primary
          dark:bg-orange-light
          w-3/5
          absolute
          left-0
          h-full
          flex flex-row-reverse
          items-center
          justify-between
          transition-transform
          duration-300
          origin-top-left
          transform
          dark:rotate-12
          dark:pl-5
          z-40
        "
      >
        <img
          src="@/assets/img/nav-break.png"
          alt=""
          class="
            h-full
            transform
            translate-x-full
            mr-1
            rotate-180
            opacity-0
            dark:opacity-100
          "
        />
        <div class="relative w-full h-full flex items-center">
          <img
            src="@/assets/img/logo-light.png"
            alt=""
            class="h-24 dark:hidden"
          />
          <img
            src="@/assets/img/logo-dark.png"
            alt=""
            class="h-24 hidden dark:block dark:animate-custom-nav-logo"
          />
        </div>
      </div>
      <div
        class="
          bg-primary
          dark:bg-orange-light
          w-2/5
          absolute
          flex
          right-0
          h-full
          items-center
          justify-between
          transition-transform
          duration-300
          origin-top-right
          transform
          dark:-rotate-12
          dark:pr-5
        "
      >
        <img
          src="@/assets/img/nav-break.png"
          alt=""
          class="
            h-full
            transform
            -translate-x-full
            ml-1
            opacity-0
            dark:opacity-100
          "
        />
        <Button
          @click="$nuxt.$store.commit('darkMode/enable')"
          class="
            transition-transform
            origin-top-right
            mr-3
            dark:mr-16
            dark:mt-8
            dark:animate-custom-nav-button
          "
        >
          Se connecter
        </Button>
      </div>
    </div>
  </nav>
</template>

<script>
export default {};
</script>
